#!/usr/bin/env bash
lolcat $(pwd)/distroInstallerSplash
echo "Welcome to LugOS..." # insert content here
# Your host distro will be installed as a strata by design, so one of the 2 lines below will error out; this is undesirable behaviour.
  
if [ "$(command -v apt)" ] && [ -f "/etc/debian_version" ]; then
    # if Ubuntu or Debian, fetch only the Arch stratum... Ubuntu also has /etc/debian_version
    # sudo apt install -y pipx
    sudo brl fetch arch
elif [ "$(command -v pacman)" ] && [ -f "/etc/arch-release" ]; then
    # If Arch, fetch only the Ubuntu stratum.
    sudo brl fetch ubuntu -m http://repo.huaweicloud.com/ubuntu -r mantic 
    # sudo brl fetch ubuntu -m http://repo.huaweicloud.com/ubuntu -r jammy 
fi

sudo sed 's/timeout = 30/timeout = 0/g' -i /bedrock/etc/bedrock.conf # set no bootloader timeout, don't complicate for users...

# setup Gnome extensions, strata does not matter anymore; use Arch stuff...
sudo pacman -S python-pipx --needed --noconfirm
pipx ensurepath >/dev/null # adds ~/.local/bin to PATH
source ~/.bashrc
# setup Gnome extensions, strata does not matter anymore; use Arch stuff...
pipx install gnome-extensions-cli  > /dev/null
pipx runpip gnome-extensions-cli install pygobject > /dev/null
sudo apt install -y nala 
export PATH=~/.local/bin:$PATH
# Define an array of extension names
extensions=(
  widgets@Aylur
  blur-my-shell@aunetx
  burn-my-windows@schneegans.github.com
  dash-to-dock@micxgx.gmail.com
  # just-perfection@alexram1313.github.io doesn't work
  
  # logo-menu@fabiomonari.it
  logomenu@aryan_k
  # pop-shell@system76.com
  forge@jmmaranan.com
  # rounded-corners@mathieu.bidon.ca
  # rounded-window-corners@yilozt.shell-extension.zip
  space-bar@luchrioh
  # top-bar-organizer@gnome-shell-extensions.gcampax.github.com
  top-bar-organizer@julian.gse.jsts.xyz
  user-theme@gnome-shell-extensions.gcampax.github.com
)

# Iterate over the extensions array and fetch each extension
for extension in "${extensions[@]}"; do
  echo "Fetching extension: $extension"
  gext install "$extension" > /dev/null
  # gext enable "$extension"
done

echo "Setting up the AUR helper..."
echo 
../terminal/setup-yay  > /dev/null
# add paru=yay=pacman thru (fish) shell aliases
yay -S tar unzip starship sassc gnome-shell-extension-extension-list xorg-xrandr --needed --noconfirm # neofetch not required

# Pentesting tools/packages
echo "Installing penetration testing utilities..."
echo 
yay -S nmap metasploit hashcat wifite john wireshark-cli wireshark-qt aircrack-ng sqlite --needed --noconfirm
yay -S zenmap burpsuite social-engineer-toolkit ngrok --needed --noconfirm
# PyPhisher's not in the AUR, installing using pipx...
pipx install pyphisher > /dev/null 
pipx install maxphisher > /dev/null # more feature-complete, made by the same author

# This will not be used anymore, bedrock installer has fixed this issue...
# curl -fsSL https://mirror.rackspace.com/archlinux/iso/2023.07.01/archlinux-bootstrap-x86_64.tar.gz > arch.tar.gz
# sudo tar -xzf arch.tar.gz
# sudo tar cf arch.tar root.x86_64/
# sudo brl import arch arch.tar

## TODO 
git clone https://github.com/lugvitc/lugfetch.git --depth 1
cd lugfetch && sudo make install && lugfetch >/dev/null && cd -
mkdir -p ~/.local/bin/
mkdir -p ~/.config/neofetch/
mkdir -p ~/.config/starship/
ln -sf $(pwd)/../neofetch/neofetch ~/.local/bin/
ln -sf $(pwd)/../neofetch/config.conf ~/.config/neofetch/
ln -sf $(pwd)/../terminal/.bashrc ~/.lug-bashrc
ln -sf $(pwd)/../terminal/starship.toml ~/.config/starship
sudo ln -sf $(pwd)/../terminal/lugpkg /usr/local/bin/
echo "[[ -f ~/.lug-bashrc ]] && source ~/.lug-bashrc " >> ~/.bashrc

# echo >> themeInfo to ~/.config/gtk-3.0/settings.ini
yay -S  gruvbox-plus-icon-theme-git --needed --noconfirm
git clone https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme.git /tmp/gruvbox
mkdir ~/.themes
cp -r /tmp/gruvbox/themes/Gruvbox-Dark-B ~/.themes/
dconf write /org/gnome/desktop/interface/gtk-theme "'Gruvbox-Dark-B'"
dconf write /org/gnome/desktop/interface/icon-theme "'Gruvbox-Plus-Dark'"
gsettings set org.gnome.shell.extensions.user-theme name "Gruvbox-Dark-B"
# Cursor Theme
yay -S bibata-cursor-theme  --needed
gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
# Fixes gtk-4.0 theming and adds Jetbrains Mono Nerd font
yay -S  ttf-jetbrains-mono-nerd --noconfirm --needed
# Sets Jetbrains Mono font for terminal
gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMonoNL Nerd Font Mono 14'

mkdir -p /usr/share/grub/themes/
if [ ! -d "/var/tmp/LUGOS-grub" ]; then
  git clone https://github.com/lugvitc/LUGOS-grub.git /var/tmp/LUGOS-grub
  sudo cp /var/tmp/LUGOS-grub/LUGOS-grub -r /usr/share/grub/themes/
fi
cd -

# sudo sed -i '47s/.*/GRUB_THEME="\/usr\/share\/grub\/themes\/LUGOS-grub\/theme.txt"/' /etc/default/grub
# sudo sed -i 's/^GRUB_THEME/GRUB_THEME="\/usr\/share\/grub\/themes\/LUGOS-grub\/theme.txt"/' /etc/default/grub
echo GRUB_THEME="/usr/share/grub/themes/LUGOS-grub/theme.txt" | sudo tee -a /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
# this SHOULD output
# Found theme: /usr/share/grub/themes/LUGOS-grub/theme.txt   

# GNOME EXTENSIONS CONFIGURATION
dconf write /org/gnome/shell/extensions/burn-my-windows/tv-glitch-enable-effect true
dconf write /org/gnome/shell/extensions/burn-my-windows/fire-enable-effect false
dconf write /org/gnome/shell/extensions/burn-my-windows/tv-glitch-animation-time 650
dconf write /org/gnome/desktop/background/picture-uri-dark "'file://$HOME/LUG_custom_distro/LUG-wallpaper-d.png'"
dconf write /org/gnome/desktop/background/picture-uri "'file://$HOME/LUG_custom_distro/LUG-wallpaper-l.png'"
dconf write /org/gnome/shell/extensions/user-theme/enabled true


# MISC CLEANUP
yay -S libadwaita-without-adwaita-git --noconfirm --needed
yay -Rns $(yay -Qtdq) --noconfirm
sudo pacman -S neovim nodejs npm --noconfirm --needed
git clone https://github.com/lugvitc/LUGOS-nvim-config.git ~/.config/nvim
