#!/usr/bin/env bash 
# Ubuntu and Arch are highly compatible with Bedrock

# Install lolcat using make (check if make/build-essential/base-devel is installed, if not, install it...) 
# sudo git clone https://github.com/jaseg/lolcat /opt/lolcat 
# cd lolcat 
# make 
# cd -

if [ "$(command -v apt)" ] && [ -f "/etc/debian_version" ]; then
    if ! [ "$(command -v lolcat &>/dev/null)" ]; then
        echo "lolcat is not installed. Attempting to install..."
        sudo apt update
        sudo apt install -y lolcat
    fi
  elif [ "$(command -v pacman)" ] && [ -f "/etc/arch-release" ]; then
    if ! [ "$(command -v lolcat &>/dev/null)" ]; then
        echo "lolcat is not installed. Attempting to install..."
        sudo pacman -S --noconfirm lolcat
    fi
# else
    # Eat 5-star
    # echo "Unsupported distribution. Kindly install lolcat and retry the installation."
    # exit
fi


echo "Welcome to our distro, LugOS. This distro post-install script sets up our configuration....."

cat ./distroInstallerSplash | lolcat # /opt/lolcat/lolcat 
sudo ./install-bedrock-x86_64 --hijack # this will eventually create a /bedrock/etc/bedrock.conf
echo "Reboot the system at your convenience, then run the postSetup script."
